Try explicit bundle install
Test run is now failing with:

Run make test
  make test
  shell: /bin/bash -e {0}
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/home/runner/work/epb-auth-tools/epb-auth-tools/Rakefile:3:in `<top (required)>'
(See full trace by running task with --trace)
make: *** [test] Error 1
Makefile:15: recipe for target 'test' failed

Grasping at straws, but maybe having an explicit bundle install will help, rather than relying on "with bundler-cache: true", which is supposed to do a bundle install for us.